import "./globals.css";
import Header from "@/components/Header";

export const metadata = {
  title: "Ridian Challenge - Federico Villa",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
